#!/bin/bash\necho 'Setting up...'
echo 'Running check 1...'
echo 'Running check 2...'
echo 'Running check 3...'
echo 'Running check 4...'
echo 'Running check 5...'
echo 'Running check 6...'
echo 'Running check 7...'
echo 'Running check 8...'
echo 'Running check 9...'
